mux: sparx5-spi: Add MODULE_LICENSE and MODULE_DESCRIPTION
If the sparx5-spi is built as a kernel module then the build will throw
a warning or an error depending on what is missing:

WARNING: modpost: missing MODULE_DESCRIPTION() in drivers/mux/mux-sparx5.o

ERROR: modpost: missing MODULE_LICENSE() in drivers/mux/mux-sparx5.o

Adding the MODULE_DESCRIPTION() and MODULE_LICENSE() seems to fix these issues.