net: microchip: vcap: export vcap_netlink_init_from_priv and vcap_netlink_uninit
vcap_netlink_init() is exported, but the underlying
vcap_netlink_init_from_priv() and the matching vcap_netlink_uninit()
were not. Consumers that build as modules (sparx5, lan9645x) fail
modpost:

    ERROR: modpost: "vcap_netlink_init_from_priv" [...mchp-lan9645x.ko] undefined!
    ERROR: modpost: "vcap_netlink_uninit" [...mchp-lan9645x.ko] undefined!

Add the missing EXPORT_SYMBOL_GPL()s.